### ISSUE TITLE
Add support to Remotes

### ISSUE THREAD

**Issue by alefragnani** [vsls-contrib/code-tour#14]
First of all, congrats for the extension! Great idea 👏 .

I tried to use it on remotes (docker), but just noted the extension still doesn’t support it. I could _Install in Container_ but I guess it wouldn’t be necessary.

I’m preparing a PR to help you with that 😁

**Comment by lostintangent** [comment]
OK awesome, thanks!

**Comment by abulka** [comment]
Confirmed also in WSL - you can record steps when editing a remote SSH project in WSL (Windows Subsystem for Linux) v1 under Windows 10 but the steps won't playback.
The extensions installs itself OK on the remote, and allows you to 'record' but nothing plays back when you hit the play button on the tour, or when you double click on any individual step of the tour.
Hopefully the merge fixes this in WSL too?

**Comment by lostintangent** [comment]
@alefragnani Can you confirm that CodeTour is still working for you when doing container-based development? Though in your case, you didn’t install the extension in the container right?

@abulka Seems like we might need a new bug to track this issue. To confirm: did you install CodeTour in the WSL context or locally?

**Comment by abulka** [comment]
I installed CodeTour in the WSL context only, and encountered the playback problem.  

I then switched to another, local project, installed CodeTour locally, and it worked for that local project.

**Comment by alefragnani** [comment]
@lostintangent ,

It's not _fully_ working 😢 . @abulka reported that it's not being able to _playback_, but in my case, I wasn't able to _record_ (playback worked perfectly). And you are right, I didn't install in the container, I used the local installation.

Then, I tested with the other releases, and noted that it stopped working with release **0.0.8**. I used the `Install Another Version..` command in VS Code.

I wasn't able to check the sources/debug the extension yet, to identify exactly where is the issue (probably tomorrow I could take a look). The 0.0.8 changelog says:

> - Added the ability to associate a tour with a specific Git tag and/or commit, in order to enable it to be resilient to code changes
> - Updated the tour recorder so that tours are automatically saved upon creation, and on each step/change_

Hope this helps

**Comment by alefragnani** [comment]
@lostintangent ,

I could find the reason behind _my scenario_ while trying to  _record tour_. It’s cause by the new “Git tag/commit association” feature.

I’m not sure why, but when connected to remotes, it’s not being able to initialize the Git API (even being a Git repo). The code below returns null:

https://github.com/vsls-contrib/codetour/blob/d7cd6ad2822ebf9fe0cebf8c4ad55e4895c32754/src/git.ts#L32

No `git` api is available and when it calls `promptForTourRef()`, it fails silently, instead of simply returning `undefined` and continue the steps:

https://github.com/vsls-contrib/codetour/blob/d7cd6ad2822ebf9fe0cebf8c4ad55e4895c32754/src/commands.ts#L508

Simply adding a check for valid `api` instance worked, but this is not a valid solution, because the remote folder, in my case, is a Git repo:

Hope this helps

**Comment by lostintangent** [comment]
@alefragnani In your case, is CodeTour installed on the UI or workspace side? I'm wondering if the problem is that CodeTour is running on the UI side, whereas your code (and the git data) is running on the workspace side.

**Comment by alefragnani** [comment]
@lostintangent It’s installed on the UI. 

I’m not sure the problem is related to _where_ the extension is installed, but on _how_ it detects `vscode.git` being installed. BTW, the `vscode.git` extension itself is correctly installed (on UI) and enabled.

**Comment by lostintangent** [comment]
Could you try installing CodeTour in the remote workspace? I'm curious if it would work in that context.

**Comment by alefragnani** [comment]
Sure I can! 

When installed in the remote workspace (using `devcontainer.json` file) it worked.

**Comment by lostintangent** [comment]
Yeah I'm not sure if `vscode.extensions.getExtension` works when the requesting extension is on the UI side, and the requested extension is on the remote/workspace side. CodeTour works fine locally, and it seems to work when installed in the remote workspace. But it seems like it has challenges when installed as a UI extension, and you're editing a remote workspace.

I'll check to see what the recommendation is for this.

**Comment by alefragnani** [comment]
Hm, do you mean the built-in extensions, like `vscode.git`, are automatically installed on the remote? Maybe that’s, why when you look at extension’s viewlet, all built-in extensions are tagged as _Extension is enabled on ‘container-name’_, instead of _This extension is enabled globally_

**Comment by lostintangent** [comment]
I believe so yeah. That's why you can install CodeTour in the remote context, and it finds `vscode.git`, without you having had to install it.

**Comment by alefragnani** [comment]
It makes sense, but if that’s the case, the remote development support (`extensionKind` tag in `package.json`) is not working as expected.

It is defined as `[“workspace”, “ui”]` and `workspace` means the extension _runs on the remote machine_. At least this is what I understand  [reading the docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds).

**Comment by lostintangent** [comment]
That setting specifies that the extension can run in either the UI or workspace side. And the ordering indicates which one "wins" if the extension is installed in both.

That said, based on what we're discussing, it actually seems like CodeTour might need to just set this to `["workspace"]`, since it expects to be able to leverage Git metadata from the workspace.

**Comment by alefragnani** [comment]
I think you are right. 

Below [in the docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) there is a better explanation, which says `[“workspace”, “ui”]` just _prefers_ `workspace` but does not have any hard requirements. 

Now, the extension requires Git, so a hard requirement was found 😁.

**Comment by alefragnani** [comment]
I see one small issue about taking that direction. The extension now _must be installed_ on every remote, no matter which kind of workspace you have (Git or not). 

Some could argue that the extension itself doesn't have a _hard requirement_ on Git, but to the Git API provided by VS Code. At least, in this case, it's exactly how it is happening. You just require another extension. You don't require a Git lib/package.
